### PR TITLE
Fix failing specs

### PR DESCRIPTION
**Pull request by mauricioszabo**

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
The changes look solid. Hate to say the version of the tester being used here is known to be broken, so I wouldn't trust it's output tbh. But lets merge it then fully look at tests during the bundle to core

**Comment by Spiker985** [comment]
Now that `action-pulsar-dependency` is stable - I merged master back into this branch. CI is passing, (but ~it~ `master` was passing before) so I'm curious is the testing was flawed before, or if it was a function of the bad tester previously

**Comment by confused-Techie** [comment]
> Now that `action-pulsar-dependency` is stable - I merged master back into this branch. CI is passing, (but ~it~ `master` was passing before) so I'm curious is the testing was flawed before, or if it was a function of the bad tester previously

It's hard to say. But if anything this likely causes failures when it's tested in our `pulsar` repo, or would once bundled. Not to sure but I recognize the pattern as something we have had to do for several other packages.

So I'm in no way opposed to this change, and think now that you fixed the testing here, and we can see this passes without issue, do you have any problem with me merging this one @Spiker985?

**Comment by Spiker985** [comment]
Not at all. I was going to ask for a second opinion from you guys

Obviously, we'll want to (basically) replace all our tests at some point, but I'm okay with this one

It shows that at the bare minimum we haven't regressed

**Comment by confused-Techie** [comment]
@Spiker985 good point, shows things are still working. In that case see no issue merging, Thanks @mauricioszabo

**Pull request merged**
